-- ============================================================================
-- ANOMALY LOGS TABLE
-- ============================================================================
-- Stores detected anomalies for historical tracking and dashboard display
-- ============================================================================

-- Create anomaly logs table
CREATE TABLE IF NOT EXISTS anomaly_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric TEXT NOT NULL CHECK (metric IN ('temperature', 'humidity')),
    value NUMERIC(6,2) NOT NULL,
    deviation NUMERIC(6,2),
    severity TEXT NOT NULL CHECK (severity IN ('low', 'medium', 'high')),
    detection_method TEXT NOT NULL,
    message TEXT,
    detected_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    acknowledged BOOLEAN DEFAULT FALSE,
    acknowledged_at TIMESTAMPTZ
);

-- Index for fast queries
CREATE INDEX IF NOT EXISTS idx_anomaly_logs_detected_at
ON anomaly_logs (detected_at DESC);

CREATE INDEX IF NOT EXISTS idx_anomaly_logs_severity
ON anomaly_logs (severity, detected_at DESC);

CREATE INDEX IF NOT EXISTS idx_anomaly_logs_unacknowledged
ON anomaly_logs (acknowledged, detected_at DESC)
WHERE acknowledged = FALSE;

-- Enable RLS
ALTER TABLE anomaly_logs ENABLE ROW LEVEL SECURITY;

-- Allow public read/insert
DROP POLICY IF EXISTS "Allow public read anomaly_logs" ON anomaly_logs;
CREATE POLICY "Allow public read anomaly_logs"
ON anomaly_logs FOR SELECT
TO anon
USING (true);

DROP POLICY IF EXISTS "Allow public insert anomaly_logs" ON anomaly_logs;
CREATE POLICY "Allow public insert anomaly_logs"
ON anomaly_logs FOR INSERT
TO anon
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update anomaly_logs" ON anomaly_logs;
CREATE POLICY "Allow public update anomaly_logs"
ON anomaly_logs FOR UPDATE
TO anon
USING (true);

-- ============================================================================
-- CLEANUP FUNCTION
-- ============================================================================
-- Delete old anomaly logs (keep last 30 days)

CREATE OR REPLACE FUNCTION cleanup_old_anomaly_logs(retention_days INT DEFAULT 30)
RETURNS BIGINT LANGUAGE plpgsql AS $$
DECLARE
    deleted_count BIGINT;
BEGIN
    DELETE FROM anomaly_logs
    WHERE detected_at < (NOW() - MAKE_INTERVAL(days => retention_days));

    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$;

-- ============================================================================
-- GET UNACKNOWLEDGED ANOMALIES
-- ============================================================================

CREATE OR REPLACE FUNCTION get_active_anomalies(max_count INT DEFAULT 50)
RETURNS TABLE (
    id BIGINT,
    metric TEXT,
    value NUMERIC,
    deviation NUMERIC,
    severity TEXT,
    detection_method TEXT,
    message TEXT,
    detected_at TIMESTAMPTZ
) LANGUAGE sql STABLE AS $$
    SELECT id, metric, value, deviation, severity, detection_method, message, detected_at
    FROM anomaly_logs
    WHERE acknowledged = FALSE
    ORDER BY
        CASE severity
            WHEN 'high' THEN 1
            WHEN 'medium' THEN 2
            ELSE 3
        END,
        detected_at DESC
    LIMIT max_count;
$$;

-- ============================================================================
-- ACKNOWLEDGE ANOMALY
-- ============================================================================

CREATE OR REPLACE FUNCTION acknowledge_anomaly(anomaly_id BIGINT)
RETURNS BOOLEAN LANGUAGE plpgsql AS $$
BEGIN
    UPDATE anomaly_logs
    SET acknowledged = TRUE, acknowledged_at = NOW()
    WHERE id = anomaly_id AND acknowledged = FALSE;

    RETURN FOUND;
END;
$$;
